import React, { useState, useEffect } from 'react';
import { FileText, Download, Printer, Filter, Calendar, Activity, ShieldAlert, Cpu } from 'lucide-react';
import { AppLayout } from '../../layouts/AppLayout';
import { alertService, Alert } from '../../services/alertService';

export const ReportsPage: React.FC = () => {
  const [generating, setGenerating] = useState(false);
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchAlerts = async () => {
      try {
        const data = await alertService.getAlerts();
        setAlerts(data);
      } catch (err) {
        console.error('Failed to load alerts for report', err);
      } finally {
        setLoading(false);
      }
    };
    fetchAlerts();
  }, []);

  const handlePrint = () => {
    window.print();
  };

  const handleExportCSV = () => {
    setGenerating(true);
    setTimeout(() => {
      let csv = "Date,Event,Severity,Device,Status\n";
      alerts.forEach(a => {
        const date = new Date(a.timestamp).toISOString();
        csv += `${date},${a.threat},${a.severity},${a.id},${a.status}\n`; // device_name isn't in alertService type directly, but threat contains it
      });
      const blob = new Blob([csv], { type: 'text/csv' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'NOC_Report_Live.csv';
      a.click();
      setGenerating(false);
    }, 500);
  };

  // Dynamic calculations
  const totalAlerts = alerts.length;
  const criticalAlerts = alerts.filter(a => a.severity === 'CRITICAL').length;
  
  // Group by threat (which contains device name)
  const alertCounts: Record<string, number> = {};
  alerts.forEach(a => {
    alertCounts[a.threat] = (alertCounts[a.threat] || 0) + 1;
  });
  
  const topGenerators = Object.entries(alertCounts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5);

  return (
    <AppLayout breadcrumbs={[{ label: 'Reports' }]}>
      <div className="flex flex-col gap-6 animate-fade-in max-w-6xl mx-auto">
        
        {/* Header (Hidden when printing) */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 print:hidden">
          <div>
            <h1 className="text-2xl font-bold text-gray-900">NOC Executive Summary</h1>
            <p className="text-sm text-gray-500 mt-1">Monthly performance and threat analytics report</p>
          </div>
          
          <div className="flex items-center gap-3">
            <button 
              onClick={handleExportCSV}
              disabled={generating}
              className="flex items-center gap-2 bg-white hover:bg-gray-50 text-gray-700 border border-gray-200 px-4 py-2 rounded-lg shadow-sm font-medium transition disabled:opacity-50"
            >
              <Download className="w-4 h-4" />
              {generating ? 'Exporting...' : 'Export CSV'}
            </button>
            <button 
              onClick={handlePrint}
              className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg shadow-sm font-medium transition"
            >
              <Printer className="w-4 h-4" /> Print PDF
            </button>
          </div>
        </div>

        {/* Printable Report Content */}
        <div className="bg-white rounded-xl shadow-card border border-gray-100 p-8 print:shadow-none print:border-none print:p-0">
          
          {/* Report Header */}
          <div className="border-b border-gray-200 pb-6 mb-8 flex items-end justify-between">
            <div>
              <h2 className="text-3xl font-black text-gray-900 tracking-tight">AI-NOC Security Report</h2>
              <p className="text-gray-500 mt-2 font-medium">Reporting Period: <span className="text-gray-900">September 1 - September 30, 2026</span></p>
            </div>
            <div className="text-right">
              <div className="inline-flex items-center gap-2 bg-blue-50 text-blue-700 px-3 py-1 rounded-full font-bold text-sm mb-2">
                <FileText className="w-4 h-4" /> CONFIDENTIAL
              </div>
              <p className="text-sm text-gray-500">Generated by Admin</p>
            </div>
          </div>

          {/* Executive Summary Stats */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
            <div className="bg-green-50/50 border border-green-100 rounded-xl p-5">
              <div className="flex items-center gap-3 mb-2">
                <Activity className="w-5 h-5 text-green-600" />
                <h3 className="font-semibold text-gray-900">Network Uptime</h3>
              </div>
              <p className="text-3xl font-black text-green-600">99.98%</p>
              <p className="text-sm text-gray-500 mt-1">+0.02% from last month</p>
            </div>

            <div className="bg-red-50/50 border border-red-100 rounded-xl p-5">
              <div className="flex items-center gap-3 mb-2">
                <ShieldAlert className="w-5 h-5 text-red-600" />
                <h3 className="font-semibold text-gray-900">Total Alerts Tracked</h3>
              </div>
              <p className="text-3xl font-black text-red-600">{totalAlerts}</p>
              <p className="text-sm text-gray-500 mt-1">{criticalAlerts} critical severity</p>
            </div>

            <div className="bg-indigo-50/50 border border-indigo-100 rounded-xl p-5">
              <div className="flex items-center gap-3 mb-2">
                <Cpu className="w-5 h-5 text-indigo-600" />
                <h3 className="font-semibold text-gray-900">Avg Utilization</h3>
              </div>
              <p className="text-3xl font-black text-indigo-600">42.5%</p>
              <p className="text-sm text-gray-500 mt-1">Peak: 84% at 14:00 daily</p>
            </div>
          </div>

          {/* Detailed Summary */}
          <div className="space-y-6">
            <div>
              <h3 className="text-lg font-bold text-gray-900 border-b border-gray-100 pb-2 mb-4">1. Threat Landscape Overview</h3>
              <p className="text-gray-700 leading-relaxed text-sm">
                During the reporting period, the AI anomaly detection engine monitored 4.2TB of simulated network traffic. The most common threat vector identified was ICMP flooding, accounting for 64% of all critical alerts. The automated mitigation system successfully isolated 12 ports suspected of hosting compromised endpoints, preventing lateral movement across the internal network.
              </p>
            </div>

            <div>
              <h3 className="text-lg font-bold text-gray-900 border-b border-gray-100 pb-2 mb-4">2. Top Alert Generators</h3>
              <table className="w-full text-sm text-left">
                <thead className="bg-gray-50 text-gray-600 font-semibold">
                  <tr>
                    <th className="px-4 py-3 rounded-tl-lg">Device Name</th>
                    <th className="px-4 py-3">Device Type</th>
                    <th className="px-4 py-3">Alerts Generated</th>
                    <th className="px-4 py-3 rounded-tr-lg">Resolution Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {topGenerators.map(([name, count], idx) => (
                    <tr key={name} className={idx % 2 === 1 ? "bg-gray-50/50" : ""}>
                      <td className="px-4 py-3 font-medium text-gray-900">{name}</td>
                      <td className="px-4 py-3 text-gray-600">Monitored Device</td>
                      <td className="px-4 py-3 font-bold text-red-600">{count}</td>
                      <td className="px-4 py-3 text-green-600 font-medium">Auto-Tracked</td>
                    </tr>
                  ))}
                  {topGenerators.length === 0 && (
                    <tr>
                      <td colSpan={4} className="px-4 py-8 text-center text-gray-500">No alerts generated in this period.</td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>

            <div>
              <h3 className="text-lg font-bold text-gray-900 border-b border-gray-100 pb-2 mb-4">3. Automated Actions Taken</h3>
              <ul className="list-disc pl-5 space-y-2 text-sm text-gray-700">
                <li>Isolated port FastEthernet0/1 on Core Switch A due to sustained SYN flood activity.</li>
                <li>Restarted GNS3 connection listener automatically 2 times after brief disconnects.</li>
                <li>Applied QoS throttling to PC-1 to prevent bandwidth starvation of critical voice VLANs.</li>
              </ul>
            </div>
          </div>
          
          <div className="mt-12 pt-6 border-t border-gray-200 text-center text-xs text-gray-400">
            CONFIDENTIAL - Internal Use Only - AI-NOC Enterprise Systems
          </div>

        </div>
      </div>
    </AppLayout>
  );
};
export default ReportsPage;
